### PR TITLE
added status check

### PR DESCRIPTION
**Pull request by MalikElate**
The check_get_status function allows our .har files to last longer. If we check that a channel exits using a get request we don't need to ping endpoint for handle availability. (side note: each har file is good for about 50 calls). 

I also added a .gitignore file to help with collaboration.

### CODE REVIEW

**Comment by maxtheaxe** [comment]
I'm not opposed to changing the underlying search to use your suggested method (I believe that's how [sherlock](https://github.com/sherlock-project/sherlock) functions as well, actually), but I have a few questions/propositions before we merge:

-  Have you had a chance to compare the number of searches you're able to perform using your method with a HAR file (as in, a signed-in user) vs. without?
- Do you have time to refactor a bit to add it as an additional search method (maybe make it default, and use the original functionality as a secondary option, functional via command line flags), rather than deleting the original altogether?
- Assuming the searches are reasonably-functional (capable of at least a few searches) without a signed in user, can you add some logic that will fall back to it if no HAR files are included?

**Comment by MalikElate** [comment]
For the last point, are you suggesting that if there is no har file, the program should resort to just running 404 checks?

**Comment by maxtheaxe** [comment]
I think that would be cool, yeah. As far as I can tell, those work just fine without authentication.

**Comment by MalikElate** [comment]
Ok, I did some testing, i was able to get about 90-100 request with the additional code, versus the previous 50. I don't have time right now working full time to refactor. Last thing, I built a ui using this check it out here https://github.com/MalikElate/handles-repo

**Comment by maxtheaxe** [comment]
A GUI sounds cool! You should clean up your readme so people can find and identify it more easily.

Someone in the youtube comments suggested something that sounds like a perfect merger of the two processes we already discussed:
image

If you (@MalikElate) or anyone else has time to take a crack at that, please feel free to submit a PR. I'm not sure when I'll have time myself.

**Comment by MalikElate** [comment]
> A GUI sounds cool! You should clean up your readme so people can find and identify it more easily.
> 
> Someone in the youtube comments suggested something that sounds like a perfect merger of the two processes we already discussed: image
> 
> If you (@MalikElate) or anyone else has time to take a crack at that, please feel free to submit a PR. I'm not sure when I'll have time myself.

The pr I opened does this haha. 

I'm keeping the gui private for now, just wanted to share with the you. Adding support for adding multiple har files soon.

**Comment by maxtheaxe** [comment]
I apologize for the ridiculous delay. I finally had time to look over your code and realize I'm dumb, you did exactly that (as you pointed out).

Merging it now, apologies again.

**Comment by MalikElate** [comment]
> I apologize for the ridiculous delay. I finally had time to look over your code and realize I'm dumb, you did exactly that (as you pointed out).
> 
> 
> 
> Merging it now, apologies again.

No problem - I did end up shipping the gui https://woodskull-software.itch.io/og-youtube-handle-finder did 0 sales 😆 

But this is what I'm building now.  https://file-converter-8j3n3n8l8-malikelates-projects.vercel.app/

**Pull request merged**
